// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.0
// source: XAAAA.proto

package XXXX

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XAAAAClient is the client API for XAAAA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XAAAAClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type xAAAAClient struct {
	cc grpc.ClientConnInterface
}

func NewXAAAAClient(cc grpc.ClientConnInterface) XAAAAClient {
	return &xAAAAClient{cc}
}

func (c *xAAAAClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/XXXX.XXXX.XAAAA/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XAAAAServer is the server API for XAAAA service.
// All implementations must embed UnimplementedXAAAAServer
// for forward compatibility
type XAAAAServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedXAAAAServer()
}

// UnimplementedXAAAAServer must be embedded to have forward compatible implementations.
type UnimplementedXAAAAServer struct {
}

func (UnimplementedXAAAAServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedXAAAAServer) mustEmbedUnimplementedXAAAAServer() {}

// UnsafeXAAAAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XAAAAServer will
// result in compilation errors.
type UnsafeXAAAAServer interface {
	mustEmbedUnimplementedXAAAAServer()
}

func RegisterXAAAAServer(s grpc.ServiceRegistrar, srv XAAAAServer) {
	s.RegisterService(&XAAAA_ServiceDesc, srv)
}

func _XAAAA_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XAAAAServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/XXXX.XXXX.XAAAA/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XAAAAServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XAAAA_ServiceDesc is the grpc.ServiceDesc for XAAAA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XAAAA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "XXXX.XXXX.XAAAA",
	HandlerType: (*XAAAAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _XAAAA_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "XAAAA.proto",
}
